### ISSUE TITLE
a bug?

### ISSUE THREAD

**Issue by tianjiangtao999** [alculquicondor/psqlparse#28]
if my sql like this:
"select (b.script_name),'中' from (select * from temp.halfisolateworkjob20171221) a left join (select * from temp.script2table) b on a.schema_name||'.'||a.table_name=b.table_name where a.create_time <'20171201' and a.owner='app_vgop' and schema_name='SESSION' and process_flag=false and b.script_name is not null order by 1;;"

how can I get the relname of sql? 

I look into the project "pg-materialize" but that project can't resolve this? if sql like this :
   CREATE MATERIALIZED VIEW IF NOT EXISTS schema1.messages_mv
              AS (
                select (b.script_name),'中' from (select * from temp.halfisolateworkjob20171221) a left join (select * from temp.script2table) b on a.schema_name||'.'||a.table_name=b.table_name where a.create_time <'20171201' and a.owner='app_vgop' and schema_name='SESSION' and process_flag=false and b.script_name is not null order by 1
              ) WITH DATA;
the program is ok,but when I delete the create ,change sql like:"elect (b.script_name),'中' from (select * from temp.halfisolateworkjob20171221) a left join (select * from temp.script2table) b on a.schema_name||'.'||a.table_name=b.table_name where a.create_time <'20171201' and a.owner='app_vgop' and schema_name='SESSION' and process_flag=false and b.script_name is not null order by 1;"
I use a method like pg-materialize to test,failed,the result is:
[<psqlparse.nodes.parsenodes.SelectStmt object at 0x7fb9c7d22590>] <type 'list'> 0
[<psqlparse.nodes.parsenodes.SelectStmt object at 0x7fb9c7d22590>] <type 'list'> 0
SELECT <class 'psqlparse.nodes.parsenodes.SelectStmt'> 1
{'dependencies': set([]), 'views': set([])}

my code like this:#！coding:utf-8

def extract_nodes(content):
    from psqlparse import parse
    from psqlparse import nodes

    class NS(object):
        pass
    ns = NS()
    ns.views = set()
    ns.dependencies = set()

    def inner(data, depth):
        print data,type(data),depth
        if isinstance(data, dict):
            
            for key, value in data.items():
                inner(value, depth)
        elif isinstance(data, list) or isinstance(data, tuple):
            print data,type(data),depth
            for item in data:
                inner(item, depth + 1)

    parsed_content = parse(content)
    inner(parsed_content, 0)
    return {
    'views': ns.views,
    'dependencies': ns.dependencies - ns.views
    }

query = """ select (b.script_name),'中' from (select * from temp.halfisolateworkjob20171221) a left join (select * from temp.script2table) b on a.schema_name||'.'||a.table_name=b.table_name where a.create_time <'20171201' and a.owner='app_vgop' and schema_name='SESSION' and process_flag=false and b.script_name is not null order by 1
             
        """
# query2=r"insert into dis.td_bd_area_info_d SELECT A.DEAL_DATE,A.INT_ID,A.ZH_LABEL,A.COUNTY_ID, B.ZH_LABEL OUNTY_NAME,B.CITY_ID,case when B.city_id = '40' then '邢台市' when B.city_id = '33' then '秦皇岛市' when B.city_id = '41' then '邯郸市' when B.city_id = '34' then '沧州市' when B.city_id = '36' then '廊坊市' when B.city_id = '32' then '石家庄市' when B.city_id = '37' then '张家口市' when B.city_id = '38' then '保定市' when B.city_id = '42' then '唐山市' when B.city_id = '43' then '衡水市' when B.city_id = '39' then '承德市'ELSE '其他' END ,CASE WHEN A.CELL_SOURCE in ('铁通割接','无线宽带','新国标','自建','自建无线宽带') and A.COVER_TYPE IN ('0','1','2','3') THEN '自建有线' WHEN A.CELL_SOURCE in ('铁通割接','无线宽带','新国标','自建','自建无线宽带') and A.COVER_TYPE IN ('4') THEN '自建无线(WLAN)' WHEN A.CELL_SOURCE in ('铁通割接','无线宽带','新国标','自建','自建无线宽带') and A.COVER_TYPE IN ('6') THEN '自建无线（4G）' WHEN A.CELL_SOURCE in ('铁通割接','无线宽带','新国标','自建','自建无线宽带') and A.COVER_TYPE IN ('6') THEN '自建无线（4G）' WHEN A.CELL_SOURCE in ('第三方割接','第三方无线宽带') and A.COVER_TYPE IN  ('0','1','2','3')  THEN '三方有线' WHEN A.CELL_SOURCE in ('第三方割接','第三方无线宽带') and A.COVER_TYPE IN  ('4') THEN '三方无线（WLAN）'  else '其他' end,case when A.AREA_TYPE = '市区(含县城)' then '市区' when A.AREA_TYPE = '乡镇(含城乡结合部)' then '乡镇' when A.AREA_TYPE = '农村' then '农村'  else '其他' end,A.CELL_SOURCE,A.COVER_TYPE,A.HOUSE_NUM,ROW_NUMBER() OVER (PARTITION BY A.INT_ID ORDER BY A.MODIFY_TIME DESC , B.MODIFY_TIME DESC ) RN FROM DW.TD_RMS_ADD_CELL_D A LEFT JOIN DW.TD_RMS_COUNTY_D B ON A.COUNTY_ID = B.INT_ID AND B.DEAL_DATE = 20170101 where A.DEAL_DATE = 20170101;"
# query="""select (b.script_name),'中' from (select * from temp.halfisolateworkjob20171221) a left join (select * from temp.script2table) b on a.schema_name||'.'||a.table_name=b.table_name where   a.create_time <'20171201' and a.owner='app_vgop' and schema_name='SESSION' and process_flag=false and b.script_name is not null order by 1;"""

print extract_nodes(query)

can you help me?thanks a lot

**Comment by alculquicondor** [comment]
Hello @tianjiangtao999,
It is pretty confusing to read your question. Can you try formatting it properly?

It seems that you are trying to implement functionality that is already there. If you know the structure of your query (meaning that it doesn't vary much), you can directly access the properties. I suggest you read the code in `psqparse/nodes.py` or try to inspect the output (using `dir`and/or `help` on the python shell). You can also try simply printing `result.tables()` (check the README).

Other than that, your code doesn't seem to insert anything on the defined set. So, it's probably not a bug in the library but your code.

BTW, are you using the released version in pip or the master version? The master version is much more advanced. We haven't released it yet because there is still work to be done.

**Comment by tianjiangtao999** [comment]
thanks for your answer.
My question is ,I want to find the table dependencies by psqlparse,but I don't know how?I try to the  result.tables(),but result is “AttributeError: 'Statement' object has no attirbute 'tables'

the program above like come from https://github.com/aanari/pg-materialize,I think the guy has the same problem.
my english is poor,so python ,so thanks for your help.

**Comment by tianjiangtao999** [comment]
And I have noticed the pip source was wrong ,I download source code to install.
Now I use the result[0]._obj to visit the parse tree.

**Comment by tianjiangtao999** [comment]
of course ,your program is good,my python is so poor to understand some function.sorry.

**Comment by alculquicondor** [comment]
Have you tried `result.tables()` on the master version (not pip).

**Comment by tianjiangtao999** [comment]
yes，it‘s my problem，I use “ python setup.py build_ext --inplace” ，otherwise "import parse",results is "

 import psqlparse

---------------------------------------------------------------------------

ImportError                               Traceback (most recent call last)

<ipython-input-1-8f14ac1d1436> in <module>()

----> 1 import psqlparse




/root/test/psqlparse-1.0rc5/psqlparse/__init__.py in <module>()

----> 1 from .parser import parse, parse_dict

" 

now that 's all ok。thanks alot

can I contact you by email?


















田江涛


13903118998@139.com


13903118998







电子名片新出VIP模板啦，快来体验>>




扫一扫,


快速添加名片到手机




--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: Aldo Culquicondor  <notifications@github.com>
 

 
 发送时间: 2018-01-16 11:28:08
 

 
 收件人:alculquicondor/psqlparse <psqlparse@noreply.github.com> 

 
 抄送:移动机房监控室田工 <13903118998@139.com>,Mention <mention@noreply.github.com> 

 
 主题: Re: [alculquicondor/psqlparse] a bug? (#28)
 



Have you tried result.tables() on the master version (not pip).

**Comment by tianjiangtao999** [comment]
My job is the database useless data cleaning, I want to use “psqlparse” find table and summary the dependent relationships between script, input is some documents contains sql, I put the SQL in psqlparse  to find their source and target table, and then record these relationships, then I can find the problems, such as some table has never been used，these table can be deleted，so I want toknow，when I have a sql (perharps insert or update),how can I find target table and source table?and then sometimes I need to find the whereclause?because  I find ,different sql's structure is different!
so I refrence the  https://github.com/aanari/pg-materialize ，this code is simple to me

**Comment by tianjiangtao999** [comment]
I find the tar file，and master and pip，different？because I try to install through three method，the result is different

**Comment by tianjiangtao999** [comment]
do you means the nodes is sample？

**Comment by alculquicondor** [comment]
I remembered I uploaded a version to pip: https://pypi.python.org/pypi/psqlparse/1.0rc5 Try that.
As for nodes.py, I meant https://github.com/alculquicondor/psqlparse/tree/master/psqlparse/nodes

**Comment by tianjiangtao999** [comment]
yes,you are right，My python‘s version is 2.6，I update it to 2.7，that's OK
