### ISSUE TITLE
Simple code issue not working working

### ISSUE THREAD

**Issue by ck090** [alculquicondor/psqlparse#29]
Hey! Alculquicondor
Your usage code itself is not running and throwing this error.
Please do help!!
![screen shot 2018-04-12 at 5 45 14 pm](https://user-images.githubusercontent.com/12717969/38677489-0bf3813a-3e7c-11e8-8d9c-afc9b3390a02.png)

**Comment by alculquicondor** [comment]
It seems that you are not on the latest version. please use version 1.0+
