### ISSUE TITLE
How do I get a parse tree?

### ISSUE THREAD

**Issue by ck090** [alculquicondor/psqlparse#31]
Hi @alculquicondor . Once again how do I get a PostgreSQL parse tree as an output.
There is no documentation provided to find out which columns are there nor where are the INSERT queries etc.
and what way is the parse tree saved and how I can further read it, for doing further computations.

`used_tables = stmt[0].tables()` like this what else functions are there and what function is used to get the entire parse tree.

**Comment by alculquicondor** [comment]
You can get a full dump of the tree (as obtained from libpg_query) like this:

```psqlparse.parse_dict(query)```

`parse` builds a tree of python objects, with specialized classes. Not all of them are there yet (refs #26). `tables` is the only helper function add the moment. It has a general implementation here https://github.com/alculquicondor/psqlparse/blob/master/psqlparse/nodes/nodes.py#L6 (a depth first search). Subclasses override the function for performance. Feel free to add new functions and contribute back.
