### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'tables'

### ISSUE THREAD

**Issue by justinfay** [alculquicondor/psqlparse#33]
There appears to be a bug with the `tables` method on certain queries.

This is reproducible using the following query

`select * from foo where (a, b) in ((1,2), (3,4)) order by a, b`

A full example from a python REPL

```python
>>> import psqlparse
>>> statements = psqlparse.parse('select * from foo where (a, b) in ((1,2), (3,4)) order by a, b')
>>> statements[0].tables()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    statements[0].tables()
  File "/home/justin/workspace/dbmerge/env/lib/python3.6/site-packages/psqlparse-1.0rc5-py3.6-l
inux-x86_64.egg/psqlparse/nodes/parsenodes.py", line 49, in tables
    _tables |= self.where_clause.tables()
  File "/home/justin/workspace/dbmerge/env/lib/python3.6/site-packages/psqlparse-1.0rc5-py3.6-l
inux-x86_64.egg/psqlparse/nodes/parsenodes.py", line 272, in tables
    _tables |= item.tables()
AttributeError: 'dict' object has no attribute 'tables'
```
I am using python 3.6.5 and installed psqlparse from a git checkout at commit dc7117afb7a704dee98fff5ebbff9b4a5c6b5a30

**Comment by justinfay** [comment]
hi @alculquicondor thanks for the response I will try to take a look at this during the week, otherwise it may be a few weeks before I will get a chance again.

**Comment by alculquicondor** [comment]
Actually, it's a different bug... we are not expecting a list of lists https://github.com/alculquicondor/psqlparse/blob/master/psqlparse/nodes/parsenodes.py#L271

**Comment by justinfay** [comment]
Hi @alculquicondor I have had a very quick look at this, could it be due to the `RowExpr` class from #26 not being implemented?
