### ISSUE TITLE
installation error ubuntu

### ISSUE THREAD

**Issue by mreguly** [alculquicondor/psqlparse#45]
I am having this error when trying install psqlparse on ubuntu. I have flex and bison installed. What can cause this problem?

Collecting psqlparse
  Using cached https://files.pythonhosted.org/packages/af/5a/a59c01632b5b9ade799cb0705de1a89d92021d554fa7f29fe27434db60be/psqlparse-0.2.5.tar.gz
Requirement already satisfied: six in /home/guliver/.virtualenvs/sql/lib/python3.6/site-packages (from psqlparse) (1.12.0)
Building wheels for collected packages: psqlparse
  Running setup.py bdist_wheel for psqlparse ... error
  Complete output from command /home/guliver/.virtualenvs/sql/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-a4rb5hkf/psqlparse/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-ixpq02gc --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/psqlparse
  copying psqlparse/__init__.py -> build/lib.linux-x86_64-3.6/psqlparse
  copying psqlparse/exceptions.py -> build/lib.linux-x86_64-3.6/psqlparse
  copying psqlparse/nodes.py -> build/lib.linux-x86_64-3.6/psqlparse
  running build_ext
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  100   127    0   127    0     0    348      0 --:--:-- --:--:-- --:--:--   349
  100 1507k    0 1507k    0     0   767k      0 --:--:--  0:00:01 --:--:-- 1032k
  ./build_libpg_query.sh: line 8: unzip: command not found
  
  An error occurred during extension building.
  Make sure you have bison and flex installed on your system.
  
  ----------------------------------------
  Failed building wheel for psqlparse
  Running setup.py clean for psqlparse
Failed to build psqlparse
Installing collected packages: psqlparse
  Running setup.py install for psqlparse ... error
    Complete output from command /home/guliver/.virtualenvs/sql/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-a4rb5hkf/psqlparse/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-omai97hh/install-record.txt --single-version-externally-managed --compile --install-headers /home/guliver/.virtualenvs/sql/include/site/python3.6/psqlparse:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/psqlparse
    copying psqlparse/__init__.py -> build/lib.linux-x86_64-3.6/psqlparse
    copying psqlparse/exceptions.py -> build/lib.linux-x86_64-3.6/psqlparse
    copying psqlparse/nodes.py -> build/lib.linux-x86_64-3.6/psqlparse
    running build_ext
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100   127    0   127    0     0    312      0 --:--:-- --:--:-- --:--:--   312
    100 1507k    0 1507k    0     0   808k      0 --:--:--  0:00:01 --:--:-- 2542k
    ./build_libpg_query.sh: line 8: unzip: command not found
    
    An error occurred during extension building.
    Make sure you have bison and flex installed on your system.
    
    ----------------------------------------
Command "/home/guliver/.virtualenvs/sql/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-a4rb5hkf/psqlparse/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-omai97hh/install-record.txt --single-version-externally-managed --compile --install-headers /home/guliver/.virtualenvs/sql/include/site/python3.6/psqlparse" failed with error code 127 in /tmp/pip-install-a4rb5hkf/psqlparse/

**Comment by lfittl** [comment]
As the log says, you will also need to have the `unzip` program available - that is required to unpack the underlying C library's source code.

**Comment by mreguly** [comment]
Thank you. That solved my issue

**Comment by maroua-zbl** [comment]
I am having this error when trying install psqlparse on windows 10 (python 64bits). Thank you to help me to solve this problem:
Collecting psqlparse
  Using cached psqlparse-0.2.5.tar.gz (23 kB)
Requirement already satisfied: six in c:\users\zeblahm\anaconda3\lib\site-packages (from psqlparse) (1.15.0)
Building wheels for collected packages: psqlparse
  Building wheel for psqlparse (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\zeblahm\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zeblahm\\AppData\\Local\\Temp\\pip-install-qni9rvc7\\psqlparse\\setup.py'"'"'; __file__='"'"'C:\\Users\\zeblahm\\AppData\\Local\\Temp\\pip-install-qni9rvc7\\psqlparse\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\zeblahm\AppData\Local\Temp\pip-wheel-i9hoddgz'
       cwd: C:\Users\zeblahm\AppData\Local\Temp\pip-install-qni9rvc7\psqlparse\
  Complete output (11 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8\psqlparse
  copying psqlparse\exceptions.py -> build\lib.win-amd64-3.8\psqlparse
  copying psqlparse\nodes.py -> build\lib.win-amd64-3.8\psqlparse
  copying psqlparse\__init__.py -> build\lib.win-amd64-3.8\psqlparse
  running build_ext
  error: [WinError 193] %1 n’est pas une application Win32 valide
  ----------------------------------------
  ERROR: Failed building wheel for psqlparse
  Running setup.py clean for psqlparse
Failed to build psqlparse
Installing collected packages: psqlparse
    Running setup.py install for psqlparse ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\zeblahm\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zeblahm\\AppData\\Local\\Temp\\pip-install-qni9rvc7\\psqlparse\\setup.py'"'"'; __file__='"'"'C:\\Users\\zeblahm\\AppData\\Local\\Temp\\pip-install-qni9rvc7\\psqlparse\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, 
'"'"'exec'"'"'))' install --record 'C:\Users\zeblahm\AppData\Local\Temp\pip-record-ze3mqc70\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\zeblahm\Anaconda3\Include\psqlparse'   
         cwd: C:\Users\zeblahm\AppData\Local\Temp\pip-install-qni9rvc7\psqlparse\
    Complete output (11 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\psqlparse
    copying psqlparse\exceptions.py -> build\lib.win-amd64-3.8\psqlparse
    copying psqlparse\nodes.py -> build\lib.win-amd64-3.8\psqlparse
    copying psqlparse\__init__.py -> build\lib.win-amd64-3.8\psqlparse
    running build_ext
    error: [WinError 193] %1 n’est pas une application Win32 valide
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\zeblahm\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zeblahm\\AppData\\Local\\Temp\\pip-install-qni9rvc7\\psqlparse\\setup.py'"'"'; __file__='"'"'C:\\Users\\zeblahm\\AppData\\Local\\Temp\\pip-install-qni9rvc7\\psqlparse\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\zeblahm\AppData\Local\Temp\pip-record-ze3mqc70\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\zeblahm\Anaconda3\Include\psqlparse' Check the logs for full command output.
PS C:\Users\zeblahm\Desktop\JOS-master\JOS-master> pip3 install psqlparse
Collecting psqlparse
  Using cached psqlparse-0.2.5.tar.gz (23 kB)
Requirement already satisfied: six in c:\users\zeblahm\anaconda3\lib\site-packages (from psqlparse) (1.15.0)
Building wheels for collected packages: psqlparse
  Building wheel for psqlparse (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\zeblahm\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zeblahm\\AppData\\Local\\Temp\\pip-install-t772smqj\\psqlparse\\setup.py'"'"'; __file__='"'"'C:\\Users\\zeblahm\\AppData\\Local\\Temp\\pip-install-t772smqj\\psqlparse\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\zeblahm\AppData\Local\Temp\pip-wheel-pu35qsry'
       cwd: C:\Users\zeblahm\AppData\Local\Temp\pip-install-t772smqj\psqlparse\
  Complete output (11 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8\psqlparse
  copying psqlparse\nodes.py -> build\lib.win-amd64-3.8\psqlparse
  copying psqlparse\__init__.py -> build\lib.win-amd64-3.8\psqlparse
  running build_ext
  error: [WinError 193] %1 n’est pas une application Win32 valide
  ----------------------------------------
  ERROR: Failed building wheel for psqlparse
  Running setup.py clean for psqlparse
Failed to build psqlparse
Installing collected packages: psqlparse
    Running setup.py install for psqlparse ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\zeblahm\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zeblahm\\AppData\\Local\\Temp\\pip-install-t772smqj\\psqlparse\\setup.py'"'"'; __file__='"'"'C:\\Users\\zeblahm\\AppData\\Local\\Temp\\pip-install-t772smqj\\psqlparse\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, 
'"'"'exec'"'"'))' install --record 'C:\Users\zeblahm\AppData\Local\Temp\pip-record-2zemt7vm\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\zeblahm\Anaconda3\Include\psqlparse'   
         cwd: C:\Users\zeblahm\AppData\Local\Temp\pip-install-t772smqj\psqlparse\
    Complete output (11 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\psqlparse
    copying psqlparse\exceptions.py -> build\lib.win-amd64-3.8\psqlparse
    copying psqlparse\nodes.py -> build\lib.win-amd64-3.8\psqlparse
    copying psqlparse\__init__.py -> build\lib.win-amd64-3.8\psqlparse
    running build_ext
    error: [WinError 193] %1 n’est pas une application Win32 valide
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\zeblahm\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zeblahm\\AppData\\Local\\Temp\\pip-install-t772smqj\\psqlparse\\setup.py'"'"'; __file__='"'"'C:\\Users\\zeblahm\\AppData\\Local\\Temp\\pip-install-t772smqj\\psqlparse\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\zeblahm\AppData\Local\Temp\pip-record-2zemt7vm\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\zeblahm\Anaconda3\Include\psqlparse' Check the logs for full command output.
