### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by alculquicondor** [alculquicondor/psqlparse#5]
We should add a few tests. Basically: pass a query an verify that the proper objects with proper properties where instantiated. Also a wrong query should be pass and verify the Exception thrown.

**Comment by sneh-vyas** [comment]
Could you please provide some details into what tests are you referring to?

**Comment by alculquicondor** [comment]
@sneh-vyas I just updated the description of the issue. Let me know if you need more details. Basically, I'm open to suggestions.
