### ISSUE TITLE
How does the output look?

### ISSUE THREAD

**Issue by Divyashivakumar10** [alculquicondor/psqlparse#51]
hey im new to this , i followed the development section and usage section .
how do i perfrom test 
what command generates the parsed tree and how do i display it on console
please help.

**Comment by alculquicondor** [comment]
There is no way to "pretty-print" the whole tree.

But you can get a rough estimate if you print the output of `parse_dict`

```
import psqlparse
statements = psqlparse.parse('SELECT * from mytable')
```
