### ISSUE TITLE
Create .travis.yml file

### ISSUE THREAD

**Issue by alculquicondor** [alculquicondor/psqlparse#7]
Basically, this should do a build of the module:

```sh
USE_CYTHON=1 python setup.py build_ext --inplace -f install
```

Once #5 is done, it should run those tests too, coverage included (see [this](http://blog.behnel.de/posts/coverage-analysis-for-cython-modules.html))

**Comment by merkkp** [comment]
I would like to give a shot on this.
As it doesn't run tests yet I understand that it should be really simple, just building and installing it?
Running tests can be added later I guess
Also against which python versions it should build?

**Comment by alculquicondor** [comment]
@merkkp right.
Target 2.7.x and 3.5.x please
